
pipeline{
  agent any
  stages{
    stage('CI'){
      steps{
        script {
            doDynamicParallelSteps()
        }
      }
    }
  }
}

def doDynamicParallelSteps(){
  def cust = ["cust1","cust2","cust3","cust4"]
  tests = [:]
  for (f in cust) {
    tests["${f}"] = {
      node {
        stage("build") {
          echo "${f}"
        }
        stage("deploy") {
          echo "${f} uihuoho"
        }
        stage("test") {
          echo "${f} uihuoho"
        }
      }
    }
  }
  parallel tests
}
